openapi: 3.0.0
info:
  version: "0.1"
  title: AWS Python Serverless Template API
  description: An API to produce a simple AWS Python Serverless Template
paths:
  /bmi:
    get:
      description: gets something
      parameters:
        - in: query
          name: height
          description: The height in centimeters
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 999
          required: true
          example: 180
        - in: query
          name: weight
          description: The weight in kilograms
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 999
          required: true
          example: 80
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BMIResponse"
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Origin:
              schema:
                type: "string"
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Origin:
              schema:
                type: "string"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Origin:
              schema:
                type: "string"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BMICalculator.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
components:
  schemas:
    BMIResponse:
      type: object
      required:
        - bmi
      properties:
        bmi:
          type: number
          format: float
          description: The Calculated BMI
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          title: The Error message
